modLoader = "javafml"
loaderVersion = "[41,)"
license = "All Rights Reserved"

[[mods]]
modId = "foodtxf"
version = "${file.jarVersion}"
displayName = "Food TXF"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/food-txf"
logoFile = "logo.png"
authors = "jahirtrap"
description = "Some useful food & cannibalism"
itemIcon = "foodtxf:diamond_knife"

[[dependencies.foodtxf]]
    modId = "forge"
    mandatory = true
    versionRange = "[41,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.foodtxf]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,1.19.2]"
    ordering = "NONE"
    side = "BOTH"
