modLoader = "javafml"
loaderVersion = "[37,)"
license = "All Rights Reserved"

[[mods]]
modId = "foodtxf"
version = "1.17.1-1.3.6-forge"
displayName = "Food TXF"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/food-txf"
logoFile = "logo.png"
authors = "jahirtrap"
description = "Some useful food & cannibalism"
itemIcon = "foodtxf:golden_beef"

[[dependencies.foodtxf]]
    modId = "forge"
    mandatory = true
    versionRange = "[37,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.foodtxf]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.17.1,1.18)"
    ordering = "NONE"
    side = "BOTH"
