package com.jahirtrap.foodtxf.init;

import com.jahirtrap.foodtxf.item.*;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Tiers;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import static com.jahirtrap.foodtxf.FoodtxfMod.MODID;

public class FoodtxfModItems {
    public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MODID);
    public static final RegistryObject<Item> PLAYER_FLESH = REGISTRY.register("player_flesh", () -> new BaseFoodItem(4, 0.375f));
    public static final RegistryObject<Item> COOKED_PLAYER_FLESH = REGISTRY.register("cooked_player_flesh", () -> new BaseFoodItem(8, 0.8f));
    public static final RegistryObject<Item> CLEAN_PUFFERFISH = REGISTRY.register("clean_pufferfish", () -> new BaseFoodItem(2, 0.1f));
    public static final RegistryObject<Item> COOKED_PUFFERFISH = REGISTRY.register("cooked_pufferfish", () -> new BaseFoodItem(6, 0.85f));
    public static final RegistryObject<Item> COOKED_TROPICAL_FISH = REGISTRY.register("cooked_tropical_fish", () -> new BaseFoodItem(6, 0.85f));
    public static final RegistryObject<Item> DOUGH_BALL = REGISTRY.register("dough_ball", () -> new BaseFoodItem(2, 0.2f));
    public static final RegistryObject<Item> TOASTED_BREAD = REGISTRY.register("toasted_bread", () -> new BaseFoodItem(8, 0.75f));
    public static final RegistryObject<Item> BREAD_SLICE = REGISTRY.register("bread_slice", () -> new BaseFoodItem(4, 0.5f));
    public static final RegistryObject<Item> TOASTED_BREAD_SLICE = REGISTRY.register("toasted_bread_slice", () -> new BaseFoodItem(6, 0.65f));
    public static final RegistryObject<Item> BAGUETTE = REGISTRY.register("baguette", () -> new BaseFoodItem(15, 0.6f, 64));
    public static final RegistryObject<Item> COOKED_CARROT = REGISTRY.register("cooked_carrot", () -> new BaseFoodItem(5, 0.7f));
    public static final RegistryObject<Item> COOKED_BEETROOT = REGISTRY.register("cooked_beetroot", () -> new BaseFoodItem(5, 0.6f));
    public static final RegistryObject<Item> PUMPKIN_SLICE = REGISTRY.register("pumpkin_slice", () -> new BaseFoodItem(4, 0.35f));
    public static final RegistryObject<Item> GOLDEN_BEEF = REGISTRY.register("golden_beef", () -> new BaseFoodItem(10, 0.8f));
    public static final RegistryObject<Item> GOLDEN_PORKCHOP = REGISTRY.register("golden_porkchop", () -> new BaseFoodItem(10, 0.8f));
    public static final RegistryObject<Item> GOLDEN_PLAYER_FLESH = REGISTRY.register("golden_player_flesh", () -> new BaseFoodItem(10, 0.8f));
    public static final RegistryObject<Item> GOLDEN_FISH = REGISTRY.register("golden_fish", () -> new BaseFoodItem(8, 0.85f));
    public static final RegistryObject<Item> GOLDEN_BREAD = REGISTRY.register("golden_bread", () -> new BaseFoodItem(10, 0.76f));
    public static final RegistryObject<Item> GOLDEN_BREAD_SLICE = REGISTRY.register("golden_bread_slice", () -> new BaseFoodItem(8, 0.625f));
    public static final RegistryObject<Item> GOLDEN_POTATO = REGISTRY.register("golden_potato", () -> new BaseFoodItem(8, 0.875f));
    public static final RegistryObject<Item> GOLDEN_BEETROOT = REGISTRY.register("golden_beetroot", () -> new BaseFoodItem(8, 0.875f));
    public static final RegistryObject<Item> GOLDEN_SWEET_BERRIES = REGISTRY.register("golden_sweet_berries", () -> new BaseFoodItem(6, 0.6f));
    public static final RegistryObject<Item> GOLDEN_GLOW_BERRIES = REGISTRY.register("golden_glow_berries", () -> new BaseFoodItem(6, 0.6f));
    public static final RegistryObject<Item> GLISTERING_PUMPKIN_SLICE = REGISTRY.register("glistering_pumpkin_slice", () -> new BaseFoodItem(7, 1f));
    public static final RegistryObject<Item> CHEESE = REGISTRY.register("cheese", () -> new BaseFoodItem(4, 0.75f));
    public static final RegistryObject<Item> CHEESE_SLICE = REGISTRY.register("cheese_slice", () -> new BaseFoodItem(2, 0.75f));
    public static final RegistryObject<Item> RAW_CHEESE_EMPANADA = REGISTRY.register("raw_cheese_empanada", () -> new BaseFoodItem(5, 0.6f));
    public static final RegistryObject<Item> RAW_MEAT_EMPANADA = REGISTRY.register("raw_meat_empanada", () -> new BaseFoodItem(5, 0.6f));
    public static final RegistryObject<Item> CHEESE_EMPANADA = REGISTRY.register("cheese_empanada", () -> new BaseFoodItem(9, 0.6f));
    public static final RegistryObject<Item> MEAT_EMPANADA = REGISTRY.register("meat_empanada", () -> new BaseFoodItem(9, 0.6f));
    public static final RegistryObject<Item> CHEESE_SANDWICH = REGISTRY.register("cheese_sandwich", () -> new BaseFoodItem(10, 0.7f));
    public static final RegistryObject<Item> THERMOS = REGISTRY.register("thermos", () -> new ThermosItem(new Item.Properties()));
    public static final RegistryObject<Item> GLASS = REGISTRY.register("glass", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> BOX = REGISTRY.register("box", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> FRUIT_SALAD = REGISTRY.register("fruit_salad", () -> new ContainerFoodItem(1, 6, 0.65f));
    public static final RegistryObject<Item> VEGETABLE_SALAD = REGISTRY.register("vegetable_salad", () -> new ContainerFoodItem(1, 6, 0.65f));
    public static final RegistryObject<Item> MIXED_SALAD = REGISTRY.register("mixed_salad", () -> new ContainerFoodItem(1, 6, 0.65f));
    public static final RegistryObject<Item> FISH_ON_STICK = REGISTRY.register("fish_on_stick", () -> new ContainerFoodItem(3, 4, 0.25f));
    public static final RegistryObject<Item> COOKED_FISH_ON_STICK = REGISTRY.register("cooked_fish_on_stick", () -> new ContainerFoodItem(3, 10, 0.7f));
    public static final RegistryObject<Item> WATER_THERMOS = REGISTRY.register("water_thermos", () -> new FluidThermosItem(1));
    public static final RegistryObject<Item> LAVA_THERMOS = REGISTRY.register("lava_thermos", () -> new FluidThermosItem(2));
    public static final RegistryObject<Item> MILK_THERMOS = REGISTRY.register("milk_thermos", () -> new FluidThermosItem(3));
    public static final RegistryObject<Item> CHOCOMILK_THERMOS = REGISTRY.register("chocomilk_thermos", () -> new FluidThermosItem());
    public static final RegistryObject<Item> GLASS_OF_FRUIT_JUICE = REGISTRY.register("glass_of_fruit_juice", () -> new ContainerFoodItem(2, 4, 0.75f, true));
    public static final RegistryObject<Item> GLASS_OF_VEGETABLE_JUICE = REGISTRY.register("glass_of_vegetable_juice", () -> new ContainerFoodItem(2, 4, 0.75f, true));
    public static final RegistryObject<Item> GLASS_OF_MIXED_JUICE = REGISTRY.register("glass_of_mixed_juice", () -> new ContainerFoodItem(2, 4, 0.75f, true));
    public static final RegistryObject<Item> GLASS_OF_WATER = REGISTRY.register("glass_of_water", () -> new ContainerFoodItem(2, 1, 1, true));
    public static final RegistryObject<Item> GLASS_OF_WATER_AND_BREAD = REGISTRY.register("glass_of_water_and_bread", () -> new ContainerFoodItem(2, 6, 0.5f));
    public static final RegistryObject<Item> GLASS_OF_LAVA = REGISTRY.register("glass_of_lava", () -> new ContainerFoodItem(2, 1, 2, true));
    public static final RegistryObject<Item> GLASS_OF_MILK = REGISTRY.register("glass_of_milk", () -> new ContainerFoodItem(2, 1, 0.5f, 3, true));
    public static final RegistryObject<Item> GLASS_OF_MILK_AND_COOKIES = REGISTRY.register("glass_of_milk_and_cookies", () -> new ContainerFoodItem(2, 5, 0.2f));
    public static final RegistryObject<Item> GLASS_OF_MILK_AND_TOASTED_BREAD = REGISTRY.register("glass_of_milk_and_toasted_bread", () -> new ContainerFoodItem(2, 10, 0.65f));
    public static final RegistryObject<Item> GLASS_OF_CHOCOMILK = REGISTRY.register("glass_of_chocomilk", () -> new ContainerFoodItem(2, 1, 1f, true));
    public static final RegistryObject<Item> GLASS_OF_CHOCOMILK_AND_COOKIES = REGISTRY.register("glass_of_chocomilk_and_cookies", () -> new ContainerFoodItem(2, 5, 0.3f));
    public static final RegistryObject<Item> GLASS_OF_CHOCOMILK_AND_TOASTED_BREAD = REGISTRY.register("glass_of_chocomilk_and_toasted_bread", () -> new ContainerFoodItem(2, 10, 0.7f));
    public static final RegistryObject<Item> BOX_OF_COOKIES = REGISTRY.register("box_of_cookies", () -> new ContainerFoodItem(0, 12, 0.325f));
    public static final RegistryObject<Item> WOODEN_KNIFE = REGISTRY.register("wooden_knife", () -> new BaseKnifeItem(Tiers.WOOD, new Item.Properties()));
    public static final RegistryObject<Item> STONE_KNIFE = REGISTRY.register("stone_knife", () -> new BaseKnifeItem(Tiers.STONE, new Item.Properties()));
    public static final RegistryObject<Item> IRON_KNIFE = REGISTRY.register("iron_knife", () -> new BaseKnifeItem(Tiers.IRON, new Item.Properties()));
    public static final RegistryObject<Item> GOLDEN_KNIFE = REGISTRY.register("golden_knife", () -> new BaseKnifeItem(Tiers.GOLD, new Item.Properties()));
    public static final RegistryObject<Item> DIAMOND_KNIFE = REGISTRY.register("diamond_knife", () -> new BaseKnifeItem(Tiers.DIAMOND, new Item.Properties()));
    public static final RegistryObject<Item> NETHERITE_KNIFE = REGISTRY.register("netherite_knife", () -> new BaseKnifeItem(Tiers.NETHERITE, new Item.Properties().fireResistant()));
    public static final RegistryObject<Item> ENDERITE_KNIFE = REGISTRY.register("enderite_knife", () -> new BaseKnifeItem(FoodtxfTiers.ENDERITE, new Item.Properties().fireResistant()));
    public static final RegistryObject<Item> STEEL_KNIFE = REGISTRY.register("steel_knife", () -> new BaseKnifeItem(FoodtxfTiers.STEEL, new Item.Properties()));
    public static final RegistryObject<Item> BRONZE_KNIFE = REGISTRY.register("bronze_knife", () -> new BaseKnifeItem(FoodtxfTiers.BRONZE, new Item.Properties()));
    public static final RegistryObject<Item> SKILLET = REGISTRY.register("skillet", () -> new BaseSkilletItem(Tiers.IRON, new Item.Properties()));
    public static final RegistryObject<Item> GOLDEN_SKILLET = REGISTRY.register("golden_skillet", () -> new BaseSkilletItem(Tiers.GOLD, new Item.Properties()));
    public static final RegistryObject<Item> DIAMOND_SKILLET = REGISTRY.register("diamond_skillet", () -> new BaseSkilletItem(Tiers.DIAMOND, new Item.Properties()));
    public static final RegistryObject<Item> NETHERITE_SKILLET = REGISTRY.register("netherite_skillet", () -> new BaseSkilletItem(Tiers.NETHERITE, new Item.Properties().fireResistant()));
    public static final RegistryObject<Item> ENDERITE_SKILLET = REGISTRY.register("enderite_skillet", () -> new BaseSkilletItem(FoodtxfTiers.ENDERITE, new Item.Properties().fireResistant()));
    public static final RegistryObject<Item> STEEL_SKILLET = REGISTRY.register("steel_skillet", () -> new BaseSkilletItem(FoodtxfTiers.STEEL, new Item.Properties()));
    public static final RegistryObject<Item> BRONZE_SKILLET = REGISTRY.register("bronze_skillet", () -> new BaseSkilletItem(FoodtxfTiers.BRONZE, new Item.Properties()));
    public static final RegistryObject<Item> CUTTING_BOARD = REGISTRY.register("cutting_board", BaseReusableItem::new);
    public static final RegistryObject<Item> MIXING_BOWL = REGISTRY.register("mixing_bowl", MixingBowlItem::new);
    public static final RegistryObject<Item> ROLLING_PIN = REGISTRY.register("rolling_pin", RollingPinItem::new);
    public static final RegistryObject<Item> JUICER = REGISTRY.register("juicer", JuicerItem::new);
    public static final RegistryObject<Item> BLENDER = REGISTRY.register("blender", BaseReusableItem::new);
    public static final RegistryObject<Item> BLACK_KITCHEN_BLOCK = block(FoodtxfModBlocks.BLACK_KITCHEN_BLOCK);
    public static final RegistryObject<Item> WHITE_KITCHEN_BLOCK = block(FoodtxfModBlocks.WHITE_KITCHEN_BLOCK);
    public static final RegistryObject<Item> LAMP = REGISTRY.register("lamp", () -> new BaseWearableItem(FoodtxfModBlocks.LAMP.get(), new Item.Properties()));
    public static final RegistryObject<Item> NETHERITE_LAMP = REGISTRY.register("netherite_lamp", () -> new NetheriteLampItem(FoodtxfModBlocks.NETHERITE_LAMP.get(), new Item.Properties()));
    public static final RegistryObject<Item> RECIPE_BOOK = REGISTRY.register("recipe_book", RecipeBookItem::new);

    private static RegistryObject<Item> block(RegistryObject<Block> block) {
        return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
    }
}
